[project]
name = "re-scout-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arxiv>=2.4.1",
    "duckduckgo-search>=8.1.1",
    "e2b-code-interpreter>=2.5.0",
    "huggingface-hub>=1.7.1",
    "langchain-anthropic>=1.4.0",
    "langchain-openai>=1.1.11",
    "langgraph>=1.1.2",
    "motor>=3.7.1",
]

[dependency-groups]
dev = [
    "langsmith>=0.7.20",
]
